version: '3.8'
services:
  db:
    image: postgres:17.5
    container_name: shippingtracker_db
    restart: always
    env_file:
    - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - "${DB_PORT}:5432"
  redis:
    image: redis:7.2-alpine
    container_name: shippingtracker_redis
    restart: always
    read_only: true
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
    - .env
    security_opt:
      - no-new-privileges:true
